#!/usr/bin/env bash
set -euo pipefail

# -----------------------------------------------------------------------------
# Alpax (अल्प) Universal 1-Click Installer for Linux & macOS
# Installs binary, downloads AI models, writes global config, and wires up
# Claude Desktop / Cursor automatically. Zero manual steps required.
# -----------------------------------------------------------------------------

BOLD="\033[1m"
GREEN="\033[32m"
CYAN="\033[36m"
YELLOW="\033[33m"
RESET="\033[0m"

header() { echo -e "\n${BOLD}${CYAN}$*${RESET}"; }
ok()     { echo -e "${GREEN}✓${RESET} $*"; }
info()   { echo -e "${YELLOW}▶${RESET} $*"; }

echo ""
echo -e "${BOLD}=========================================================="
echo -e "          Alpax (अल्प) Universal 1-Click Installer"
echo -e "==========================================================${RESET}"
echo ""

HOME_DIR="${HOME:-~}"
ALPAX_HOME="${HOME_DIR}/.alpax"
MODELS_DIR="${ALPAX_HOME}/models"
BIN_DIR="${HOME_DIR}/.local/bin"
GLOBAL_CONFIG="${ALPAX_HOME}/alpax.toml"
DB_DIR="${ALPAX_HOME}/db"

mkdir -p "${MODELS_DIR}" "${BIN_DIR}" "${DB_DIR}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd || echo "")"
LOCAL_BINARY=""
if [ -n "${SCRIPT_DIR}" ] && [ -f "${SCRIPT_DIR}/../target/release/alpax" ]; then
    LOCAL_BINARY="${SCRIPT_DIR}/../target/release/alpax"
fi

# ── 1. Install Binary ──────────────────────────────────────────────────────
header "Step 1/4 — Installing Alpax binary"

TARGET_BIN="${BIN_DIR}/alpax"
if [ -n "${LOCAL_BINARY}" ] && [ -f "${LOCAL_BINARY}" ]; then
    info "Copying prebuilt binary to ${TARGET_BIN}..."
    cp -f "${LOCAL_BINARY}" "${TARGET_BIN}"
    chmod +x "${TARGET_BIN}"
else
    if command -v cargo >/dev/null 2>&1; then
        info "Building from source via cargo (this takes ~2 minutes)..."
        cargo install --path "${SCRIPT_DIR}/../crates/server" --root "${HOME_DIR}/.local" --quiet
    else
        echo "Error: No prebuilt binary and cargo is not installed." >&2
        exit 1
    fi
fi
ok "Binary installed at: ${TARGET_BIN}"

export PATH="${BIN_DIR}:${PATH}"

# ── 2. Download Models ─────────────────────────────────────────────────────
header "Step 2/4 — Downloading AI embedding models"

MODEL_FILE="${MODELS_DIR}/all-MiniLM-L6-v2.onnx"
TOKENIZER_FILE="${MODELS_DIR}/tokenizer.json"

MODEL_URL="https://huggingface.co/Xenova/all-MiniLM-L6-v2/resolve/main/onnx/model_quantized.onnx"
TOKENIZER_URL="https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer.json"

_download() {
    local url="$1" dest="$2" label="$3"
    if [ -f "${dest}" ]; then
        ok "${label} already exists — skipping download"
        return
    fi
    info "Downloading ${label}..."
    if command -v curl >/dev/null 2>&1; then
        curl -fL --progress-bar "${url}" -o "${dest}"
    elif command -v wget >/dev/null 2>&1; then
        wget -q --show-progress "${url}" -O "${dest}"
    else
        echo "Error: Neither curl nor wget found." >&2; exit 1
    fi
    ok "${label} downloaded."
}

_download "${MODEL_URL}"      "${MODEL_FILE}"      "Embedding model (~22MB)"
_download "${TOKENIZER_URL}"  "${TOKENIZER_FILE}"  "Tokenizer (~450KB)"

# ── 3. Interactive Config Setup ────────────────────────────────────────────
header "Step 3/4 — Configuration"
echo ""
echo "We will now write your global Alpax configuration to:"
echo "  ${GLOBAL_CONFIG}"
echo "You can always edit this file later to change settings."
echo ""

# Helper: prompt with a default value
_prompt() {
    local question="$1" default="$2" var_name="$3"
    local response
    echo -ne "  ${question} [${default}]: "
    read -r response
    response="${response:-$default}"
    printf -v "${var_name}" "%s" "${response}"
}

# Determine sensible default DB path (per-project vs global)
DEFAULT_DB="${DB_DIR}"

_prompt "Chunk size (lines per code snippet)" "50"  CFG_CHUNK_SIZE
_prompt "Chunk overlap (lines shared between snippets)" "10" CFG_OVERLAP

# Validate numeric inputs
if ! [[ "${CFG_CHUNK_SIZE}" =~ ^[1-9][0-9]*$ ]]; then
    echo "  Invalid chunk size '${CFG_CHUNK_SIZE}', using default 50." >&2
    CFG_CHUNK_SIZE=50
fi
if ! [[ "${CFG_OVERLAP}" =~ ^[0-9]+$ ]]; then
    echo "  Invalid overlap '${CFG_OVERLAP}', using default 10." >&2
    CFG_OVERLAP=10
fi

# Write global config file
cat > "${GLOBAL_CONFIG}" <<TOML
# Alpax (अल्प) — Global Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit this file to change global defaults.
# A project-local alpax.toml in your repo root takes precedence.

model      = "${MODEL_FILE}"
tokenizer  = "${TOKENIZER_FILE}"
db         = "${DEFAULT_DB}"
chunk_size = ${CFG_CHUNK_SIZE}
chunk_overlap = ${CFG_OVERLAP}
TOML

ok "Global config written to: ${GLOBAL_CONFIG}"

# ── 4. Auto-configure MCP Clients ─────────────────────────────────────────
header "Step 4/4 — Wiring up MCP clients"

# Claude Desktop
CLAUDE_CONFIG=""
if [ "$(uname)" = "Darwin" ]; then
    CLAUDE_CONFIG="${HOME_DIR}/Library/Application Support/Claude/claude_desktop_config.json"
else
    CLAUDE_CONFIG="${HOME_DIR}/.config/Claude/claude_desktop_config.json"
fi

if [ -d "$(dirname "${CLAUDE_CONFIG}")" ]; then
    python3 - <<PYEOF 2>/dev/null || true
import json, os
path = '${CLAUDE_CONFIG}'
data = {}
if os.path.exists(path):
    with open(path) as f:
        data = json.load(f)
data.setdefault('mcpServers', {})['alpax'] = {'command': '${TARGET_BIN}', 'args': []}
with open(path, 'w') as f:
    json.dump(data, f, indent=2)
print('✓ Alpax registered in Claude Desktop config: ' + path)
PYEOF
fi

# Cursor IDE (stores MCP config in ~/.cursor/mcp.json)
CURSOR_MCP="${HOME_DIR}/.cursor/mcp.json"
if [ -d "${HOME_DIR}/.cursor" ]; then
    python3 - <<PYEOF 2>/dev/null || true
import json, os
path = '${CURSOR_MCP}'
data = {}
if os.path.exists(path):
    with open(path) as f:
        data = json.load(f)
data.setdefault('mcpServers', {})['alpax'] = {'command': '${TARGET_BIN}', 'args': []}
with open(path, 'w') as f:
    json.dump(data, f, indent=2)
print('✓ Alpax registered in Cursor IDE config: ' + path)
PYEOF
fi

# Ensure ~/.local/bin is in the shell's PATH permanently
SHELL_RC=""
case "${SHELL:-/bin/sh}" in
    */zsh)  SHELL_RC="${HOME_DIR}/.zshrc" ;;
    */bash) SHELL_RC="${HOME_DIR}/.bashrc" ;;
    */fish) SHELL_RC="${HOME_DIR}/.config/fish/config.fish" ;;
    *)      SHELL_RC="${HOME_DIR}/.profile" ;;
esac

PATH_LINE='export PATH="$HOME/.local/bin:$PATH"'
if [ -f "${SHELL_RC}" ] && ! grep -q ".local/bin" "${SHELL_RC}" 2>/dev/null; then
    echo "" >> "${SHELL_RC}"
    echo "# Added by Alpax installer" >> "${SHELL_RC}"
    echo "${PATH_LINE}" >> "${SHELL_RC}"
    ok "Added ~/.local/bin to PATH in ${SHELL_RC}"
fi

# ── Summary ────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}=========================================================="
echo -e "  🎉  Alpax is ready to use!"
echo -e "==========================================================${RESET}"
echo ""
echo "  Binary:       ${TARGET_BIN}"
echo "  Models:       ${MODELS_DIR}"
echo "  Config:       ${GLOBAL_CONFIG}"
echo "  Vector DB:    ${DEFAULT_DB}  (auto-created per project)"
echo ""
echo -e "${BOLD}How to use:${RESET}"
echo ""
echo "  In any AI editor that supports MCP (Claude Desktop, Cursor,"
echo "  Cline, Windsurf, Antigravity) just ask your assistant:"
echo ""
echo "    'Where is the authentication logic in this codebase?'"
echo ""
echo "  Alpax automatically indexes your project on the first query"
echo "  and keeps it in sync with every subsequent request."
echo ""
echo -e "${BOLD}Manual MCP config (if needed):${RESET}"
echo ""
echo '  "mcpServers": {'
echo '    "alpax": { "command": "'"${TARGET_BIN}"'" }'
echo '  }'
echo ""
if [ -n "${SHELL_RC}" ]; then
    echo "  Restart your terminal or run: source ${SHELL_RC}"
    echo "  to make the 'alpax' command available in PATH."
    echo ""
fi
